# This file is auto-generated by generate_keys.py
# It contains the public half of the Ed25519 key-pair used for activation
# verification. DO NOT edit manually.

PUBLIC_KEY_BYTES = bytes([140, 201, 168, 243, 97, 219, 199, 1, 69, 26, 123, 146, 199, 238, 181, 122, 151, 40, 216, 153, 171, 32, 152, 202, 205, 186, 239, 50, 199, 223, 253, 95])
